- name: Configure rancher catalogs
  uri:
    method: PUT
    status_code: 200
    user: "{{ rancher_api_key }}"
    password: "{{ rancher_api_secret }}"
    body:
      id: catalog.url
      source: Database
      name: catalog.url
      value: "{{ rancher_catalogs | to_json | string }}"
    body_format: json
    url: "{{ rancher_master_url }}/v2-beta/settings/catalog.url"
